apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
     app: simple-pod
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: simple-container
      ports:
         - containerPort:8080