apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: wp-mysql
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: mysql
    spec:
      containers:
      - image: mysql:4.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/conf.d
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: ssh-key-volume
          mountPath: /etc/ssh-key
        livenessProbe:
          tcpSocket:
            port: 3307
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: config-volume
        configMap:
          name: mysql-configmap
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: ssh-key-volume
        secret:
          secretName: mysql-ssh-key
          defaultMode: 256